In [148]:
import numpy as np
import pandas as pd

In [149]:
movies = pd.read_csv('/content/sample_data/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/sample_data/tmdb_5000_credits.csv')

In [150]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [151]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [152]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [153]:
movies = movies.merge(credits,on='title')

In [154]:
credits.shape

(4803, 4)

In [155]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [156]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [157]:
# features to keep
# genres
# id
# keywords
# title
# overview
# cast
# crew
#realse date can be kept but here we're dropping due to numerical type

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [158]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [159]:
movies.dropna(inplace=True)

In [160]:
movies.duplicated().sum()

np.int64(0)

In [161]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [162]:
# [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# ['Action','Adventure','Fantasy','SciFi']

In [163]:
import ast
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [164]:
movies['genres']=movies['genres'].apply(convert)

In [165]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [166]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [167]:
movies['keywords'] = movies['keywords'].apply(convert)

In [168]:
movies['keywords'].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [169]:
def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [170]:
movies['cast'] = movies['cast'].apply(convert3)

In [171]:
movies['cast'].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

In [172]:
def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

In [173]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [174]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [175]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [176]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [177]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [178]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [179]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [180]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [181]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [182]:
new_df = movies[['movie_id','title','tags']]

In [183]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_595/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [184]:
new_df['tags'].head()

0    In the 22nd century, a paraplegic Marine is di...
1    Captain Barbossa, long believed to be dead, ha...
2    A cryptic message from Bond’s past sends him o...
3    Following the death of District Attorney Harve...
4    John Carter is a war-weary, former military ca...
Name: tags, dtype: object

In [185]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [186]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_595/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [187]:
new_df['tags'].head()

0    in the 22nd century, a paraplegic marine is di...
1    captain barbossa, long believed to be dead, ha...
2    a cryptic message from bond’s past sends him o...
3    following the death of district attorney harve...
4    john carter is a war-weary, former military ca...
Name: tags, dtype: object

In [188]:
# will vectors of words jisme hamein similarity score pata chale do movies ki jo ham recommend kr sake
#fro this we will use bag of words or tfidf vectorizer
# closest vectors are selected
# vectorization mein will not use stop words

In [189]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [190]:
vectors = cv.fit_transform(new_df['tags']).toarray() # kaafi values zero hai toh countervectorizer jo output return krta hai vo by default sparse  matrix hota hai and usko ham numpy array mein convert kardege

In [191]:
vectors.shape

(4806, 5000)

In [192]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [193]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [194]:
feature_names = cv.get_feature_names_out()

for word in feature_names:
    print(word)

000
007
10
100
11
12
13
14
15
16
17
18
18th
18thcentury
19
1930s
1940s
1950s
1960s
1970s
1980
1980s
1985
1990s
19th
19thcentury
20
200
2009
20th
21st
23
24
25
30
300
3d
40
50
500
60
60s
70
70s
aaron
aaroneckhart
abandoned
abducted
abigailbreslin
abilities
ability
able
aboard
abuse
abusive
academy
accept
accepted
accepts
access
accident
accidental
accidentally
accompanied
accomplish
account
accountant
accused
ace
achieve
act
acting
action
actionhero
actions
activist
activities
activity
actor
actors
actress
acts
actual
actually
adam
adams
adamsandler
adamshankman
adaptation
adapted
addict
addicted
addiction
adolescence
adopt
adopted
adoption
adopts
adrienbrody
adult
adultanimation
adultery
adulthood
adults
advantage
adventure
adventures
advertising
advice
affair
affairs
affect
affection
affections
afghanistan
africa
african
africanamerican
aftercreditsstinger
afterlife
aftermath
age
aged
agedifference
agency
agenda
agent
agents
aggressive
aging
ago
agree
agrees
ahead
aid
aidanquinn
aided
aids
ailing
air
airplane
airplanecrash
airport
aka
al
alabama
alan
alaska
albert
alcohol
alcoholic
alcoholism
alecbaldwin
alex
alfredhitchcock
ali
alice
alien
alieninvasion
alienlife
alienplanet
aliens
alike
alive
allen
alliance
allied
allies
allow
allows
ally
alongside
alpacino
alter
alternate
alternative
alzheimer
amanda
amandapeet
amandaseyfried
amateur
amazing
ambassador
ambition
ambitious
ambulance
ambush
america
american
americanabroad
americanfootball
americans
amid
amidst
amnesia
amp
amsterdam
amusementpark
amy
amyadams
amysmart
analyst
anarchiccomedy
ancient
ancientrome
ancientworld
anderson
andiemacdowell
andrew
android
andy
andygarcía
angel
angelabassett
angeles
angelinajolie
angels
anger
anglee
angry
animal
animalattack
animalhorror
animals
animated
animation
anna
annafaris
anne
annehathaway
annemoss
annettebening
annie
anniversary
announces
annual
anonymity
answer
answers
ant
antarctic
anthology
anthony
anthonyanderson
anthonyhopkins
anthonymackie
anthropomorphism
anti
antics
antihero
antoinefuqua
antoniobanderas
antonyelchin
apart
apartheid
apartment
ape
apes
apocalypse
apocalyptic
apparent
apparently
appear
appears
apple
appointed
apprentice
approach
approaches
approaching
april
aquarium
arab
arch
archaeologist
archeology
archer
architect
arctic
area
aren
arena
argument
arise
aristocrat
armed
arms
army
arnold
arnoldschwarzenegger
arrangedmarriage
arrangement
arrest
arrested
arrival
arrive
arrived
arrives
arriving
arrogant
art
arthur
article
artificial
artificialintelligence
artist
artistic
artists
arts
ashes
ashley
ashleyjudd
ashtonkutcher
asia
aside
ask
asked
asking
asks
aspirations
aspiring
assassin
assassinate
assassination
assassins
assault
assigned
assignment
assistant
assumes
asteroid
astronaut
astronauts
asylum
athlete
atomicbomb
attack
attacked
attacks
attempt
attempting
attempts
attending
attends
attention
attitude
attorney
attracted
attraction
attractive
audience
audiences
audition
august
aunt
austin
australia
australian
author
authorities
authority
autism
auto
avenge
average
avoid
awaits
awakens
award
away
awry
ax
babe
baby
bachelor
backdrop
background
backgrounds
bad
bag
bahamas
bail
balance
ball
ballet
baltimore
band
bandits
bangkok
banished
bank
banker
bankrobber
bankrobbery
bar
barely
bargained
barn
barney
barry
barrylevinson
barrysonnenfeld
bars
base
baseball
based
basedoncomicbook
basedongraphicnovel
basedonnovel
basedonplay
basedonstagemusical
basedontrueevents
basedontruestory
basedontvseries
basedonvideogame
basedonyoungadultnovel
basement
basketball
batman
battle
battlefield
battles
battling
bay
beach
bear
bears
beast
beasts
beat
beating
beautiful
beautifulwoman
beauty
becky
becominganadult
bed
bedroom
bee
beer
befriends
began
begin
beginning
begins
behavior
beings
belief
beliefs
believe
believed
believes
believing
beloved
ben
benaffleck
beneath
benfoster
beniciodeltoro
benjamin
benjaminbratt
benkingsley
bennett
benstiller
bent
berlin
best
bestfriend
bet
beth
betrayal
betrayed
bettemidler
better
betty
beverly
bible
big
bigger
biggest
biker
bikini
billhader
billionaire
billmurray
billnighy
billpaxton
billpullman
billy
billybobthornton
billycrudup
billycrystal
biography
bird
birth
birthday
bisexual
bishop
bit
bite
bitter
bizarre
black
blackmagic
blackmail
blackpeople
blade
blame
blind
bliss
block
blonde
blood
bloodsplatter
bloodthirsty
bloody
blow
blue
board
boarding
boardingschool
boat
bob
bobby
bobbyfarrelly
bobhoskins
bodies
body
bodyguard
bold
bollywood
bomb
bombing
bond
bonds
bone
book
books
border
bored
boredom
boring
born
boss
boston
botched
bound
boundaries
bounty
bountyhunter
bourne
box
boxer
boxing
boy
boyfriend
boys
bradleycooper
bradpitt
brain
brand
brave
bravery
brazil
brazilian
break
breakdown
breaking
breaks
brendanfraser
brendangleeson
brent
brettratner
brian
briandepalma
bride
bridge
brief
brien
bright
brilliant
bring
bringing
brings
brink
britain
british
britishsecretservice
brittanymurphy
broadway
broke
broken
broker
brooklyn
brooks
brothel
brother
brotherbrotherrelationship
brothers
brothersisterrelationship
brought
brown
bruce
brucewillis
brutal
brutality
brutally
bryansinger
buck
buddies
buddy
buddycomedy
budget
build
building
built
bully
bullying
bumbling
bunny
burglar
buried
bus
bush
business
businessman
bust
busy
butcher
butler
butt
buy
buzz
cabin
caesar
cage
cairo
cal
california
called
calling
calls
calvin
camcorder
came
camera
cameraman
cameras
camerondiaz
camp
campaign
campbell
camping
campus
canada
canadian
cancer
candidate
candy
canine
cannibal
canuxploitation
capable
caper
capital
capitalism
capt
captain
captive
capture
captured
captures
car
caraccident
carchase
carcrash
card
care
career
carefree
cares
caretaker
careymulligan
caribbean
carjourney
carl
carlagugino
carmen
carol
carolina
carrace
carrie
carry
carrying
cars
cartel
carter
cartoon
caryelwes
case
caseyaffleck
cash
casino
cast
castle
cat
cataclysm
catastrophe
catch
catches
cateblanchett
catherinekeener
catherinezeta
catholic
catholicism
cattle
caught
cause
caused
causes
causing
cavalry
cave
celebrate
celebrated
celebration
celebrity
cellphone
cemetery
center
centered
centers
central
centuries
century
ceremony
certain
chain
chainsaw
challenge
challenged
challenges
champion
championship
chance
change
changed
changes
changing
channingtatum
chaos
chaotic
chapter
character
characters
charge
charged
charismatic
charles
charlie
charliesheen
charlizetheron
charlotte
charm
charming
chase
chased
chauffeur
cheating
cheerleader
chef
chemical
cher
chicago
chicken
chief
child
childabuse
childhero
childhood
children
chilling
china
chinese
chip
chiwetelejiofor
chloe
chloëgracemoretz
chloësevigny
chocolate
choice
choices
choose
chosen
chowyun
chris
chriscolumbus
chriscooper
chrisevans
chrishemsworth
chrisklein
chrispine
chrisrock
christ
christian
christianbale
christianity
christianslater
christinaapplegate
christinaricci
christine
christmas
christmasparty
christopher
christopherlloyd
christophernolan
christopherplummer
christopherwalken
christophwaltz
chronicle
chronicles
chuck
church
cia
cigarettesmoking
cillianmurphy
cinema
circle
circuit
circumstances
circus
cities
citizens
city
civil
civilization
civilwar
claim
claims
claire
clairedanes
clan
clark
clash
class
classes
classic
classmate
classmates
classroom
claudevandamme
clay
clean
clear
clerk
client
clients
climate
climbing
clinteastwood
clique
cliveowen
clock
clone
cloning
close
closed
closer
club
clubs
clues
clutches
coach
coast
cocaine
code
cody
coffin
cohen
col
cold
coldwar
cole
colin
colinfarrell
colinfirth
collapse
colleague
colleagues
collect
collection
collector
college
collide
collins
collision
colonel
colony
color
colorado
colorful
coma
combat
combined
come
comeback
comedian
comedic
comedy
comes
comet
comfort
comic
comics
coming
comingofage
comingout
command
commander
commercial
commit
commitment
committed
common
communication
community
companion
company
compete
competing
competition
complete
completely
complex
complicated
complications
composer
computer
computervirus
conan
concert
conclusion
condition
conditions
confederate
confession
confidence
confident
conflict
confront
confronted
confronts
confused
congress
conman
connected
connecticut
connection
connections
connects
connell
connie
connor
conquer
conscience
consequences
conservative
considered
conspiracy
conspire
constant
constantly
construction
consumed
contact
contain
contemporary
contend
contest
continue
continues
continuing
contract
control
controlled
controlling
controversial
convention
converge
convict
convicted
convince
convinced
convinces
cook
cooking
cool
cooper
cop
cope
cops
core
corner
corners
corporate
corporation
corpse
corrupt
corruption
cost
costume
couldn
count
country
countrymusic
countryside
county
coup
couple
couples
courage
courageous
course
court
courtcase
courteneycox
courtroom
cousin
cover
covert
cow
cowardliness
cowboy
crab
crack
craig
crash
crashes
crazy
create
created
creates
creation
creator
creature
creatures
credit
creepy
crew
crime
crimefighter
crimes
criminal
criminals
crisis
critical
crocodile
crook
crooked
cross
crossdressing
crossed
crosses
crown
crucifixion
cruel
cruelty
cruise
crush
crystal
cuba
cubagoodingjr
cult
cultfilm
cultural
culture
cultureclash
cunning
cup
cure
curious
current
curse
cursed
custody
customers
cut
cyberpunk
cyborg
dad
daily
dakotafanning
damage
dan
danaykroyd
dance
dancer
dancing
danger
dangerous
dangers
daniel
danielcraig
danielday
danielradcliffe
danny
dannyboyle
dannydevito
dannyglover
dare
daring
dark
darkcomedy
darkest
darkness
date
dates
dating
daughter
daughters
dave
david
davidarquette
davidduchovny
davidfincher
davidgordongreen
davidmorse
davido
davis
daxshepard
day
days
dc
dccomics
dea
dead
deadly
deaf
deal
dealer
dealers
dealing
deals
dean
death
deathofafriend
deathpenalty
deaths
debt
debut
decade
decades
decapitation
deceased
deceit
deception
decide
decided
decides
decision
decisions
dedicated
deeds
deep
deeper
deeply
defeat
defend
defense
deliver
delivers
delusion
demanding
demands
demimoore
demon
demonic
demonicpossession
demons
dennisdugan
dennishopper
dennisquaid
dentist
denzelwashington
department
depressed
depression
deputy
deranged
derek
descend
desert
deserted
designed
desire
desires
desolate
despair
desperate
desperately
desperation
despite
destined
destiny
destroy
destroyed
destroying
destruction
details
detective
detectives
determination
determine
determined
detroit
devastating
develop
developed
develops
device
devil
devoted
diabolical
dialogue
diamond
diane
dianekeaton
dianekruger
dianelane
diary
dick
dictator
did
didn
die
died
diego
dies
differences
different
difficult
digging
dignity
diner
dinner
dinosaur
dinosaurs
dire
directed
direction
director
dirt
dirty
dirtycop
disabled
disappear
disappearance
disappeared
disappears
disaster
disastrous
discover
discovered
discovering
discovers
discovery
disease
disfigurement
disgraced
disguise
dishonesty
disillusioned
disney
disorder
dispatched
distant
district
distrust
disturbed
disturbing
diva
divided
division
divorce
divorced
dj
dna
doc
doctor
document
documentary
documents
does
doesn
dog
dogs
doing
doll
dollar
dollars
dolphin
dolphlundgren
domination
don
donaldpetrie
donaldsutherland
doncheadle
donnell
doomed
doomsday
door
doorstep
doppelganger
dorothy
double
doublelife
doubt
doubts
doug
douglas
dougliman
dr
dracula
drag
dragon
drama
dramatic
draw
drawing
drawn
draws
dream
dreams
drew
drewbarrymore
drifter
drink
drinking
drive
driven
driver
drives
driving
drop
drowning
drug
drugabuse
drugaddiction
drugdealer
druglord
drugs
drugtraffic
drunk
drunken
du
dualidentity
dude
duel
duke
dumped
duo
duringcreditsstinger
dustinhoffman
dutch
duty
dwarves
dwaynejohnson
dying
dyinganddeath
dylan
dynamic
dynasty
dysfunctional
dysfunctionalfamily
dystopia
dystopicfuture
eager
earlier
early
earn
earth
earthquake
east
easy
eating
eccentric
economic
economy
eddie
eddiegriffin
eddiemurphy
edge
edharris
editor
education
edward
edwardburns
edwardnorton
effort
efforts
egg
ego
egypt
egyptian
el
elaborate
elderly
election
elements
eliaskoteas
elijahwood
eliminate
elisabethshue
elite
elizabeth
elizabethbanks
ella
ellenburstyn
ellenpage
ellie
elliot
ellis
elusive
elves
elvis
embark
embarking
embarks
embassy
embroiled
emerge
emergency
emerges
emilehirsch
emily
emilyblunt
emilymortimer
emilywatson
emma
emmastone
emmathompson
emmawatson
emotional
emotionally
emotions
emperor
empire
employee
employees
employer
employs
encounter
encounters
end
ended
ending
endless
endoftheworld
ends
enemies
enemy
energy
enforcement
engaged
engagement
engineer
england
english
enigmatic
enjoy
enlist
enlists
enormous
ensemblecast
ensues
entangled
enter
enterprise
enters
entertainer
entertaining
entire
entirely
entity
environment
environmental
epic
epidemic
era
eric
ericbana
erin
ernest
eroticism
erupts
escapade
escape
escaped
escapefromprison
escapes
escaping
escort
especially
espionage
establishment
estate
estranged
eternal
ethan
ethanhawke
eugenelevy
europe
european
eva
evacuation
evade
evamendes
evanrachelwood
eve
evening
event
events
eventually
everybody
everyday
evidence
evil
evolution
ewanmcgregor
ex
exact
exactly
examines
exchange
exciting
exclusive
execution
executive
exercise
exist
existed
existence
existentialism
exists
exorcism
exotic
exoticisland
expectations
expected
expects
expedition
experience
experienced
experiences
experiencing
experiment
expert
explorers
explores
exploring
explosion
explosive
expose
exposed
exposes
extra
extramaritalaffair
extraordinary
extraterrestrial
extraterrestrialtechnology
extreme
extremely
extremeviolence
eye
eyes
face
faced
faces
facility
facing
fact
factions
factory
fail
failed
failing
fails
fairy
fairytale
faith
fake
fall
fallen
falling
fallinginlove
falls
falseidentity
falselyaccused
fame
famed
families
family
familyrelationships
famkejanssen
famous
fan
fangvamp
fans
fantasies
fantastic
fantasy
fantasyworld
far
farewell
farm
farmer
farmhouse
fascinated
fashion
fast
faster
fat
fatal
fate
fateful
father
fatherdaughterrelationship
fathersonrelationship
favorite
fbi
fbiagent
fear
fears
fearsome
feature
features
featuring
federation
feel
feeling
feelings
feels
feet
fellow
female
femalefriendship
femalenudity
femaleprotagonist
festival
feud
fi
fiancee
fiancé
fiancée
fiction
fictional
fictionalplace
field
fields
fierce
fifth
fight
fighter
fighters
fighting
fights
figure
figures
filled
film
filmdirector
filmed
filming
filmmaker
filmmakers
filmmaking
filmproducer
films
final
finale
finally
financial
finding
finds
fine
finish
finn
fired
firm
fish
fisherman
fishing
fishoutofwater
fistfight
fit
fix
flame
flashback
flee
flees
flesh
flight
fling
flint
flirt
flood
florida
flower
fly
flying
flyingsaucer
focus
focuses
foil
follow
followed
following
follows
food
foot
footage
football
footchase
forbidden
forbiddenlove
force
forced
forces
forcing
ford
foreign
forest
forestwhitaker
forever
forget
forgiveness
form
formidable
forms
formula
fort
fortune
fortuneteller
forward
foster
fought
foundfootage
fourth
fox
framed
france
franchise
francis
francisco
francisfordcoppola
frank
frankenstein
frankie
frankoz
fraternity
fraud
freak
fred
freddieprinzejr
freddy
free
freed
freedom
freeman
freeze
french
fresh
freshman
friend
friendly
friends
friendship
frightening
frog
fromragstoriches
frontier
frozen
frustrated
fu
fueled
fugitive
fulfill
fully
fun
fund
funeral
funny
furious
future
futuristic
fword
gabrielbyrne
gaelgarcíabernal
gain
galaxy
gambler
gambling
game
games
gandhi
gang
gangs
gangster
gangsterboss
gangsters
gangwar
garage
garden
garfield
garrymarshall
gary
garygray
garyoldman
garysinise
gas
gasstation
gather
gave
gay
gayinterest
gayrelationship
genehackman
general
generation
generations
genetic
genetically
genetics
genius
genocide
gentle
geoffreyrush
george
georgeclooney
georgia
gerardbutler
german
germans
germany
getaway
gets
getting
ghetto
ghost
ghosts
giant
giants
gift
gifted
gig
girl
girlfriend
girlfriends
girls
given
gives
giving
gladiator
glamorous
glass
global
globe
glory
goal
god
gods
goes
going
gold
golden
golf
gone
good
goodvsevil
gordon
gore
gorgeous
gorilla
gossip
got
gotham
gothamcity
government
governor
grace
grade
gradually
graduate
graduation
grand
grandfather
grandmother
grant
grave
great
greater
greatest
greece
greed
greedy
greek
green
greg
gregkinnear
gregorypeck
grew
grief
grieving
griffin
grim
grisly
gritty
ground
group
groupoffriends
grow
growing
growingup
grown
grows
gruesome
guard
guardian
guerrilla
guest
guests
guide
guilt
guilty
guitar
gun
gunfight
gunman
guns
gunslinger
guru
gusvansant
guy
guypearce
guys
gwynethpaltrow
hacker
hair
half
hall
halleberry
halloween
hallucination
hand
handed
hands
handsome
handtohandcombat
hang
hanging
hangs
hannah
happen
happened
happening
happens
happily
happiness
happy
hara
harbor
hard
harlem
harmony
harold
haroldramis
harrisonford
harry
harsh
hart
harvard
harvey
harveykeitel
hasn
hatches
hate
hatred
haunt
haunted
hauntedhouse
haunting
haven
having
havoc
hawaii
haydenchristensen
head
headed
heading
headquarters
heads
healing
health
hear
heard
hearing
hears
heart
heartattack
heartbreak
hearted
hearts
heather
heathergraham
heathledger
heaven
heavily
heavy
heavymetal
heir
heiress
heist
held
helen
helenabonhamcarter
helenhunt
helenmirren
helicopter
hell
help
helped
helping
helps
henchmen
henry
hero
heroes
heroic
heroin
heroism
hidden
hiddencamera
hide
hides
hiding
high
higher
highest
highlands
highly
highschool
highschoolsports
highschoolstudent
highway
hijack
hijacking
hilarious
hilaryduff
hilaryswank
hill
hills
himalaya
hip
hippie
hire
hired
hires
historic
historical
historicalfigure
history
hit
hitchhiker
hitman
hits
ho
hobbit
hockey
hold
holding
holds
hole
holiday
holly
hollywood
holmes
holy
home
homeinvasion
homeland
homeless
homelessperson
homes
hometown
homicidal
homicide
homophobia
homosexuality
honey
honeymoon
hong
hongkong
honor
hood
hoodlum
hook
hop
hope
hopedavis
hopelessly
hopes
hoping
hopper
horrible
horrific
horrifying
horror
horrors
horse
horsebackriding
horserace
hospital
host
hostage
hostile
hostility
hot
hotel
hotelroom
hotshot
hour
hours
house
household
housekeeper
housewife
housing
howard
huge
hughgrant
hughjackman
human
humananimalrelationship
humanity
humankind
humans
humiliation
humor
hundreds
hunger
hungry
hunt
hunted
hunter
hunters
hunting
hurricane
husband
hustler
hypnosis
hyun
ianmckellen
ice
icecube
iconic
idea
idealistic
identities
identity
idol
idyllic
ignoring
ii
iii
il
ill
illegal
illegalimmigration
illegalprostitution
illness
image
imaginary
imagination
imagined
imax
immediately
immigrant
immigrants
immigration
immortal
immortality
impact
imperial
important
impossible
imprisoned
imprisonment
inadvertently
incest
incident
include
includes
including
increasingly
incredible
independence
independent
independentfilm
india
indian
indiana
indianlead
indians
individual
industry
infamous
infant
infected
infection
infidelity
infiltrate
influence
informant
information
inhabitants
inheritance
inherits
initially
injured
injury
inmates
inner
innocence
innocent
insane
insanity
inside
insists
insomnia
inspector
inspiration
inspire
inspired
inspires
inspiring
installment
instant
instantly
instead
institution
instructor
insurance
intelligence
intelligent
intends
intense
intent
intentions
intergalactic
international
internet
interrogation
interspeciesromance
intertwine
interview
interviews
intimate
intrigue
introduces
invaders
invading
invasion
invention
inventor
investigate
investigates
investigating
investigation
investigator
investment
invisible
invites
involved
involves
involving
iowa
ira
iran
iranian
iraq
ireland
irish
island
isn
isolated
isolation
israel
israeli
issues
italian
italy
ivanreitman
jack
jackblack
jackie
jackiechan
jacknicholson
jackson
jadapinkettsmith
jail
jake
jakegyllenhaal
james
jamescaan
jamescameron
jamesfranco
jamesivory
jamesmangold
jamesmarsden
jamesmcavoy
jameswan
jameswoods
jamie
jamiefoxx
jamieleecurtis
jane
janitor
japan
japanese
jaredleto
jason
jasonbateman
jasonbiggs
jasonlee
jasonschwartzman
jasonsegel
jasonstatham
javierbardem
jay
jaychandrasekhar
jayroach
jazz
jealous
jealousy
jean
jeanreno
jedi
jeff

In [195]:
['loved','loving','love']
['love','love','love'] #after applying stemming

['love', 'love', 'love']

In [196]:
import nltk

In [197]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer() #object

In [198]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [199]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_595/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [200]:
ps.stem('loved')

'love'

In [201]:
ps.stem('danced')

'danc'

In [202]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [203]:
#Higher dimensions mein euclidean distance is not perfect instead we use cosinedistanc

In [204]:
from sklearn.metrics.pairwise import cosine_similarity

In [205]:
similarity[0].shape

(4806,)

In [206]:
similarity = cosine_similarity(vectors)

In [207]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(539, np.float64(0.25038669783359574)),
 (1192, np.float64(0.24779731389167606)),
 (507, np.float64(0.24283093212859141)),
 (260, np.float64(0.2409900932515112)),
 (1214, np.float64(0.23939494881986934))]

In [208]:
similarity[0] #peheli  movie ka harr movie ke sath distance dikha ra hai

array([1.        , 0.08740748, 0.05827165, ..., 0.02418254, 0.02564946,
       0.        ])

In [209]:
similarity[1]

array([0.08740748, 1.        , 0.06451613, ..., 0.02677398, 0.        ,
       0.        ])

In [210]:
sorted(similarity[0],reverse=True)

[np.float64(1.0000000000000002),
 np.float64(0.25038669783359574),
 np.float64(0.24779731389167606),
 np.float64(0.24283093212859141),
 np.float64(0.2409900932515112),
 np.float64(0.23939494881986934),
 np.float64(0.233785950059759),
 np.float64(0.23174488732966075),
 np.float64(0.23084512921915967),
 np.float64(0.23084512921915967),
 np.float64(0.2294157338705618),
 np.float64(0.21677749238103003),
 np.float64(0.21629522817435),
 np.float64(0.21526419295572297),
 np.float64(0.21486752129677),
 np.float64(0.21296183592613546),
 np.float64(0.21239769762143662),
 np.float64(0.21239769762143662),
 np.float64(0.2108663315950723),
 np.float64(0.20857039859669466),
 np.float64(0.20770324619863198),
 np.float64(0.20751433915982237),
 np.float64(0.20395079136182276),
 np.float64(0.20395079136182276),
 np.float64(0.2029530274475215),
 np.float64(0.2029530274475215),
 np.float64(0.2024645717996314),
 np.float64(0.19767387315371682),
 np.float64(0.19466570535691505),
 np.float64(0.19194297398747862),
 np.float64(0.19117977822546817),
 np.float64(0.19088542889273336),
 np.float64(0.19088542889273336),
 np.float64(0.18848425873126295),
 np.float64(0.18731716231633883),
 np.float64(0.18731716231633883),
 np.float64(0.18541926977182405),
 np.float64(0.18539590986372861),
 np.float64(0.1842105263157895),
 np.float64(0.18172434016970185),
 np.float64(0.1813690625275029),
 np.float64(0.1810898182317451),
 np.float64(0.18074256993863339),
 np.float64(0.18074256993863339),
 np.float64(0.17954621161490197),
 np.float64(0.17954621161490197),
 np.float64(0.177343107178349),
 np.float64(0.177343107178349),
 np.float64(0.17699808135119718),
 np.float64(0.17699808135119718),
 np.float64(0.17521916101261562),
 np.float64(0.1745025152241333),
 np.float64(0.17206180040292132),
 np.float64(0.16943474841747155),
 np.float64(0.1692777916923361),
 np.float64(0.1691275228729346),
 np.float64(0.16742770563222897),
 np.float64(0.16556654463313053),
 np.float64(0.16556654463313053),
 np.float64(0.16481712868606585),
 np.float64(0.16452254913212452),
 np.float64(0.16452254913212452),
 np.float64(0.16350382386265752),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076252),
 np.float64(0.16222142113076252),
 np.float64(0.15907119074394446),
 np.float64(0.15907119074394446),
 np.float64(0.15789473684210528),
 np.float64(0.15747244473304667),
 np.float64(0.15609763526361567),
 np.float64(0.15609763526361567),
 np.float64(0.15585730003983933),
 np.float64(0.15585730003983933),
 np.float64(0.15389675281277312),
 np.float64(0.15328483487124145),
 np.float64(0.152008377581442),
 np.float64(0.15061880828219448),
 np.float64(0.15018785229652765),
 np.float64(0.14910501299480672),
 np.float64(0.14808721943977307),
 np.float64(0.14808721943977307),
 np.float64(0.14673479641335554),
 np.float64(0.14673479641335554),
 np.float64(0.14567913668701626),
 np.float64(0.14567913668701626),
 np.float64(0.14509525002200235),
 np.float64(0.14509525002200233),
 np.float64(0.14509525002200233),
 np.float64(0.1442149876003076),
 np.float64(0.14350946197048198),
 np.float64(0.1433848336691011),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.1411956236812263),
 np.float64(0.1404878717372541),
 np.float64(0.13977653617040256),
 np.float64(0.1391037210186643),
 np.float64(0.1391037210186643),
 np.float64(0.1391037210186643),
 np.float64(0.13834289277321493),
 np.float64(0.13834289277321493),
 np.float64(0.13834289277321493),
 np.float64(0.13764944032233706),
 np.float64(0.13710212427677043),
 np.float64(0.13710212427677043),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13518451760896877),
 np.float64(0.13518451760896877),
 np.float64(0.13497638119975428),
 np.float64(0.13497638119975428),
 np.float64(0.13369695534647594),
 np.float64(0.13369695534647594),
 np.float64(0.13334518676566626),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13112201362143713),
 np.float64(0.1302565123238377),
 np.float64(0.130066495428618),
 np.float64(0.12988108336653278),
 np.float64(0.12988108336653278),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12892051277806202),
 np.float64(0.12824729401064427),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.126673647984535),
 np.float64(0.126673647984535),
 np.float64(0.12565617248750865),
 np.float64(0.12565617248750865),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12487810821089254),
 np.float64(0.12487810821089254),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699315),
 np.float64(0.12262786789699315),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12166606584807191),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.1204950466257556),
 np.float64(0.1204950466257556),
 np.float64(0.1204950466257556),
 np.float64(0.11980845957463077),
 np.float64(0.11959121830873498),
 np.float64(0.11959121830873498),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.116543309349613),
 np.float64(0.116543309349613),
 np.float64(0.11587244366483038),
 np.float64(0.11587244366483038),
 np.float64(0.11587244366483038),
 np.float64(0.1147078669352809),
 np.float64(0.1147078669352809),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.1139194873735864),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11239029738980326),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11037769642208699),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10743376064838502),
 np.float64(0.10743376064838502),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.10650358071057624),
 np.float64(0.10650358071057624),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10390486669322622),
 np.float64(0.10385162309931599),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.10301070542879115),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10203255357771539),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.1003911722115382),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09694584179118516),
 np.float64(0.0967301666813349),
 np.float64(0.09567297464698798),
 np.float64(0.09558988911273408),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09304036594559835),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09183979479633063),
 np.float64(0.09176629354822471),
 np.float64(0.09176629354822471),
 np.float64(0.09086217008485092),
 np.float64(0.09086217008485092),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09012301173931252),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.0891313035643173),
 np.float64(0.08903057122447033),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08646430798325933),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08520286456846099),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.0830812984794528),
 np.float64(0.0830812984794528),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303291),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08175191193132876),
 np.float64(0.08175191193132876),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08048436365855338),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.07987230638308718),
 np.float64(0.0792740035289418),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07768997059248714),
 np.float64(0.0770085628656519),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07664241743562072),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),

In [211]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [212]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [213]:
new_df.iloc[1214].title

'Aliens vs Predator: Requiem'

In [216]:
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))